{
  name = "saxpy-cuda-test";

  containers.container =
    { pkgs, ... }:
    {
      environment.systemPackages = [
        pkgs.cudaPackages.saxpy
      ];

      # Misc cuda mounts.
      # This was generated by running:
      #   nix run nixpkgs#nix-required-mounts $(nix-instantiate -E 'derivation {name = "needs-cuda"; builder = "-"; system = "-"; requiredSystemFeatures = ["cuda"]; }') | grep -v '^/nix/store'warning
      virtualisation.systemd-nspawn.options = [
        "--bind=/host/run/opengl-driver:/run/opengl-driver"
        "--bind=/dev/dri:/dev/dri"

        # needed on AMD systems with ZLUDA:
        "--bind=/dev/kfd:/dev/kfd"
        "--bind=/sys/devices/virtual/kfd:/sys/devices/virtual/kfd"

        # needed on NVIDIA systems:
        #"--bind=/dev/nvidia-modeset:/dev/nvidia-modeset"
        #"--bind=/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
        #"--bind=/dev/nvidiactl:/dev/nvidiactl"
        #"--bind=/dev/nvidia-uvm:/dev/nvidia-uvm"
        #"--bind=/dev/nvidia0:/dev/nvidia0"
        #"--bind=/dev/nvidiactl:/dev/nvidiactl"
      ];
    };

  testScript = /* python */ ''
    container.start()

    output = container.succeed("saxpy 2>&1")
    assert "Max error: 0.000000" in output
  '';
}
